name: Minishell CI
run-name: Norminette + Compilation ğŸš€
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Norminette:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install norminette

      - name: Check norminette
        run: |
          echo "ğŸ” Running norminette..."
          norminette -R CheckForbiddenSourceHeader . | grep -v OK
          echo "âœ… Norminette check completed!"


  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make clang libreadline-dev

      - name: Clean and compile
        run: |
          echo "ğŸ”¨ Compiling minishell..."
          make
          echo "âœ… Compilation successful!"