name: Minishell CI
run-name: Norminette + Compilation ğŸš€
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Norminette:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install norminette

      - name: Check norminette
        run: |
          echo "ğŸ” Running norminette..."
          ! norminette $(find sources includes libft/includes libft/src -name "*.c" -o -name "*.h" | grep -v debug) | grep -v "GLOBAL_VAR_DETECTED" | grep -v Error


  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make clang libreadline-dev

      - name: Clean and compile
        run: |
          make fclean
          echo "ğŸ”¨ Compiling minishell..."
          make
          echo "âœ… Compilation successful!"